#+SETUPFILE: ../aux/head.org
#+TITLE: Bored now

* Bored now

[2013-05-01 Wed]

I just read a BBC article about Jimmy Wales called "Boring university
lectures are doomed" and the title and the tone of the article made me
angry. As a boring university lecturer, I felt I should speak out.

/For a counterpoint to the views expressed below, see my more recent/
/blog post on [[flip.org][lecture-flipping]]. I have mellowed as the years have/
/passed./

As an undergraduate, I sat through many boring university
lectures. Since September, I have been employed by University College
London to deliver boring university lectures and have been doing just
that. Just this morning I submitted an application for funding to help
us film some of those boring lectures and make them available (to our
students and potentially the rest of the world) online. I'm doing
these things because I think that lectures are a great way of
communicating, even if the lecturer is boring, as long as the audience
is good.

Next year I will be teaching a boring course called "Lie groups and
Lie algebras". This is an introduction to the study of abstract
symmetry in its most general and useful form: I will explain to my
students how to understand rotations in higher dimensional spaces; how
this allows you to understand the orbital structure of the hydrogen
atom without actually solving Schroedinger's equation; how the
hexagonal weight diagrams of representations of the group SU(3)
inspired Gell-Mann and Ne'eman to invent the concept of quarks, one of
the fundamental constituents of matter.

All very, very boring. I almost fell asleep typing it.

Though there have been many books and papers written about Lie groups
and Lie algebras since their development in the 1880s, there is no
book which takes quite the approach I want to take. So I will write a
comprehensive set of lecture notes and will stand up for thirty hours
and explain the ideas to my students. Not all in one go. That would be
boring, even by my standards.

And people will come.

Some people will come because they want to pass the exam. I wish them
the best of luck.

Some people may come because they think it will be an easy option. I
wish them the best of luck.

Some people will come because they genuinely want to hear what I will
say; because it's nice to hear someone who has thought hard about a
subject talking about that subject. And sometimes a lot easier than
reading their lecture notes. A lecture course is like a story: a long,
complicated story and not the kind you would read your children in bed
(I lie; when I have kids I will try this). People who have been to a
lecture course will come away with a particular view of the subject,
not just details and minutiae which they could find elsewhere. Most
importantly, they will get an idea of what details they should worry
about and what details are unimportant. That comes about as the result
of an extended conversation, a couple of hours every week. I'd have
that conversation one-to-one if I could, but I have 168 students and
other things to do.

** Structured discussion

In the article I read, Jimmy Wales expressed the view that lectures
should be replaced by online videos followed by classes in which the
material is discussed. This may work for some courses. But not
all. For a start, such discussion must be heavily structured: if you
just ask people "what did you not understand from the video?" the
responses will vary from "everything" to "nothing" to "I didn't watch
the video". And if you're structuring the discussion, why not
structure it around the story? Why not tell them the story and ask
them to stop you when they don't understand and ask for clarification?
And how does that differ from a lecture?

You could try structuring the discussion around explanatory examples,
but to be honest that's how I try to structure the story. You could
try structuring the discussion around problems and questions, but we
already have those discussions: they're called problem classes and are
an equally (if not more) important component of the degree
course. Maybe we should have more of them? That's fine as long as the
students are prepared to do more questions.

Relying on student-led interactivity is fine, provided the students
are interactive. For many reasons, difficult to control, a particular
class may not be interactive in a useful way: too many dominant
personalities, not enough dominant personalities, intimidating or
apathetic individuals who change the whole mood of the class. The
format of a lecture gives individuals a safety net: a particularly
reticent class will still learn, a particularly enthusiastic class can
turn it into more of a structured discussion.

Making videos of lectures available afterwards seems like a more
workable idea, reinforcing what they have already seen. Sometimes you
need to see something twice or more to get it. Our students are
already inundated with difficult ideas and information. I'd rather
present them with the opportunity to see it again than provide them
with too many different videos to watch. Having said that...

** Videos

...I have seen Khan's fifteen-minute videos and I think they're
wonderful. I have tried to emulate them, with mixed success: you can
see the results on Youtube. Some people like them, some people think
my teaching style is flawed. Such feedback is welcome (I'm always
ready to learn) but there are lots of teachers out there, so you don't
have to like my teaching style. Judging by the number of views, the
most useful videos I've produced are the ones where I picked something
I explained badly in class and explained it again (either verbatim or
through an example). Of course you don't know which these are until
after class when people say "I didn't understand".

I think Khan's style of videos are an effective method of teaching and
ultimately I think academics will take it up more and more. But to say
that they should replace lectures seems bizarre: I think it's
patronising to assume that our students have fifteen minute attention
spans. These videos are at best a supplement to lectures. Lectures are
there to give a bigger view on the world, how it all fits
together. Some last an hour, some last two hours. Some people get
bored.

** Boredom

While I'm at it, I also think it's patronising to assume that our
students are bored and not getting anything out of lectures. They're
at university because they're enthusiastic and interested in their
subject. They want to learn about vector calculus, about
representation theory, about studying functions on
infinite-dimensional space. They know the material is painful and
difficult, many of them relish that fact: it's why we study our
subject, to break open our minds and experience the wonder of
comprehending a difficult and beautiful idea. Sure, you can try to
jazz it up with technology, but at some point the pain and the effort
kick in and there is some extremely hard work to be done.

If you didn't want to think for yourself, you shouldn't have signed up
for a degree.

** Interruptions

Jimmy Wales says that he thinks lectures should have a pause facility
which means they need to be online. I agree that would help when
you're revising or reviewing material and particularly if the lecture
is being given in a foreign language. But I'd contend that live
lectures have a much more useful pause facility. You put up your hand.

Or if the lecturer's antisocial and talks into the blackboard, you
shout out.

You say "Could you write bigger?" or "Could you explain that again?"
or "Could you give us another example? Slower?" or "What does
‘cohomology' mean?". Some lecturers might not like it. I do. I would
like to think of lectures as structured discussion rather than an
exercise in dictation.

My students last year were great at this and my lectures were
punctuated with wonderful questions and comments like: "Which of those
ys have dots on them?", "We still can't see the dots from the back"
and "Could you just use a different notation?".

Some students are too shy for that, you might argue. They're worried
about feeling stupid in front of their peers. Their peers who are
sitting around, equally perplexed, but silent, who inwardly want to
ask the very same questions. They're going to have to take
responsibility for their own learning sooner or later. Part of
university is about learning how to learn, how to ask questions and
get the information you want. When academics mutter disgruntledly
about spoonfed students who have been mollycoddled by the system, this
is what they mean. A lecture class will get much more out of their
lecturer if they show that they're engaged, if they actively seek out
the answers to the questions inside their heads, if they try to iron
out the conflicts in their own understanding. Terry Tao, the Fields
Medallist, recommends asking yourself "dumb" questions as a great way
of learning, even (/especially) for researchers, because if you can't
work out the answer to a "dumb" question then the question is not dumb
(and nor are you).

** Alternatives

Jimmy Wales says that when he was being taught by a boring lecturer he
went and found some video tapes about calculus instead. I fully
empathise. I have done the same thing many times. Indeed, universities
are full of resources for people who want to learn about stuff. One of
those resources is lectures. If you know how to use them, you will get
a lot out of them, even if you're bored. As technology moves on, so
will the range of resources available: screencasts, online discussion
forums, wikis. We should experiment with all of these and see what
they have to offer. But that's no reason to cut out lectures, which
form the core of the university mathematics experience.

There are times when they're deeply inspiring, times when they're
incomprehensible and, yes, times when they're deadly boring. But if
you, as a student, engage with them and actively try to get something
from them then you'll find that lectures are can be as effective a
means of communicating as the best-written book or the best-planned
video.

