#+SETUPFILE: ../aux/head.org
#+TITLE: Is the speed of light constant?

* Is the speed of light constant?

[2016-08-09 Tue]

I recently came across
[[https://en.wikisource.org/wiki/A_proof_of_the_constancy_of_the_velocity_of_light][
a beautiful argument due to De Sitter (1913)]], which gave the
(first?) experimental evidence that light moves with a constant speed.

Constancy of the speed of light is one of those things that always
bothered me, and I spent a couple of days recently trying to unbother
myself. De Sitter's argument is what finally satisfied me. Below, I’m
going to explain the background, then I'll explain De Sitter's
argument. The De Sitter paper is only a couple of paragraphs long and
is available via Wikisource, so if you don't need the introductory
remarks in the blogpost below, just follow the link above and read it.

** The assumptions behind relativity

Einstein's theory of relativity is based on two fundamental
assumptions:

1. (Constancy of the speed of light) That light moves with a constant
   speed $c$, independently of how it is produced. For example, a lamp
   at rest in your living room will emit light travelling at speed
   $c$, just as a lamp on a distant spaceship moving at 3 million
   miles per hour will emit light that travels at speed $c$.

2. (Principle of relativity) That the results of experiments performed
   in inertial frame (no external forces acting, like gravity) will
   always be the same independently of the frame chosen. In other
   words, if two experimenters are drifting past each other in empty
   space, it's impossible to do an experiment to tell which of them is
   actually moving (only that they're moving relative to one another).

This second assumption always seemed completely reasonable to me, and
the first assumption always seemed kind of strange. To see why these
two assumptions give interesting consequences, we consider an
experiment first performed by Michelson and Morley in the 1880s.

** The Michelson-Morley experiment

Set up an experiment as follows. Send a beam of light in direction A,
then split it into two beams moving at right angles (one still going
in direction A, the other in direction B perpendicular to A). Place
two mirrors a fixed distance $d$ from the beam splitter so that the
two beams reflect back and recombine where they started ("the
origin”). Because the two beams travel the same distance ($2d$) in the
same time, they are "in phase" when they recombine, which means that
there is no interference between the beams (by constrast, if one of
the mirrors were closer than distance d then one of the beams will
arrive back sooner, so the beams will be out of phase and will usually
interfere with one another).

Now give the whole apparatus a kick in the A-direction so that it
starts moving with velocity $v$ in the A-direction. The light beam
moving in the A-direction has slightly further to travel on the
journey out because the mirror is moving away from it, but it has less
distance to travel on the journey back because the origin is moving
towards it. Overall, it travels the same distance as before. By
contrast, the light beam moving in the B-direction now has to travel
further! It needs to go from the origin to the B-mirror and back
(which is the same perpendicular distance as before) but it also needs
to move forwards to keep up with the moving apparatus. Suppose it
takes the B-lightbeam a time $t$ to reach the B-mirror; in this time,
the apparatus moves forward a distance $vt$, so (by Pythagoras's
theorem) the light has travelled a distance $\sqrt{d^2+v^2t^2}$. Since
light always moves with speed c, this distance is equal to $ct$, so
\[ct=\sqrt{d^2+v^2t^2},\] which means that \[t=d/\sqrt{c^2-v^2}.\] In
total, then, the light has to move a distance
$2dc/\sqrt{c^2-v^2}=2d/\sqrt{1-v^2/c^2}$, which is strictly further
than the distance $2d$ travelled by beam A. The two beams will surely
arrive back out of phase and will interfere with one another.

However, Michelson and Morley observed no such interference. Indeed,
if they had observed interference, it would have contradicted
Einstein's second assumption (the principle of relativity), because
they could have figured out their speed $v$ by measuring the
interference! Relativity explains how to modify the above analysis so
that the beams arrive back in phase: you incorporate the factor of
$1/\sqrt{1-v^2/c^2}$ into the coordinate change between the moving frame
and the rest frame, which we can think of as a "length contraction" of
the experimental apparatus observed by the observer at rest (but not
by the moving experimenter).

You see: once we make these two assumptions (constancy of light speed
and the principle of relativity) we soon run into relativistic
corrections to our classical Newtonian intuition.

** An alternative assumption

Now here's what bothered me. Let's drop the first assumption
(constancy of the speed of light) and replace it by the following
at-first-sight-equally-plausible assumption:

- Light produced by a source moving with velocity $v$ will travel at
  velocity $v+c$.

Here $c$ could be any vector whose length is the usual speed of
light. For example, we imagine that the lamp on the spaceship
(velocity $v$) is hurling out photons in all directions: those going
forwards (in the direction of the spaceship) travel at speed $c+v$ miles
per hour, those emitted backwards travel at speed $c-v$, those emitted
sideways travel at speed $c$. This, of course, is completely consistent
with the principle of relativity: someone sitting on the spaceship
next to the lamp will see these photons behaving like usual photons,
someone outside the spaceship (at rest) will notice the photons moving
with different speeds, but that will simply tell them that they are
moving relative to the source of the photons.

This theory was actually posited by Ritz in 1908 – three years after
Einstein's. On the face of it, Ritz's assumption seems much more
natural than assumption 1. Moreover, it's completely consistent with
the outcome of the Michelson-Morley experiment: it's a nice exercise
in velocity vector addition to check that if your light beams behave
the way I just described then they will arrive back at the origin in
phase without needing to invoke some crazy relativistic corrections.

** So why is the speed of light constant?

When I realised this, I wanted to re-convince myself that constancy of
the speed of light is a sensible assumption. Here are three different
ways to convince yourself of this.

- In Maxwell's theory of electromagnetism, the components of the
  electromagnetic field satisfy the wave equation with speed
  $c$. Since light is supposed to be an electromagnetic wave, this
  means it will move with speed $c$. If you know some vector calculus
  and you want to see a quick derivation of the wave equation starting
  from Maxwell's equations, Wikipedia has it.

This is the textbook explanation, and is ultimately the best
theoretical reason to believe the assumption. Indeed, Einstein's work
was mostly motivated by theoretical considerations underpinning
Maxwell's equations and their interpretation. The influence of
Maxwell's theory on his thought is clear; indeed, his original paper
is called "Zur Elektrodynamik bewegter Körper" ("On the
electrodynamics of moving bodies") and the opening paragraph explains
the particular paradox which bothered Einstein: namely, that if you
have a conductor moving in a magnetic field, there is an induced
current (according to Maxwell's theory), but that the source of this
current is either an induced electric field or a Lorentz force exerted
by the magnetic field depending on whether you're looking at the
problem from the point of view of the conductor or the magnet.

So it's safe to say that light moves at a constant speed because
Maxwell tells you so. However, this explanation is less convincing if
you don't know about the wave equation. Indeed, if you were really
skeptical about relativistic effects like length contraction and time
dilation, you might be tempted to say "Maybe the relativistic
corrections should be made to Maxwell's theory, rather than to
Newtonian mechanics?". So I want to offer two more explanations: one
is a heuristic about waves (essentially saying that Maxwell's
predictions are what you should have expected as a reasonable,
fin-de-siècle physicist) and one is De Sitter's experiment.

- Light exhibits many behaviours which are analogous to sound waves or
  water waves. For example, it refracts when it passes through
  different media, it diffracts when it passes through a grating, and
  it can be made to interfere with itself (no giggling). Sound waves
  in air travel at 768 miles per hour, regardless of whether they're
  produced by someone singing in the bath or by a passing low-flying
  jet (I say low-flying because the speed of sound does depend on the
  air pressure, which is lower at high altitudes). This is precisely
  the assumption we're making about light! But because the speed of
  sound is so much slower than that of light, it's easier to check
  this constancy in experiments. Indeed, sound is so slow that it's
  possible for a very fast aeroplane to fly faster than 768mph, in
  which case it is travelling faster than the sound it is producing,
  giving rise to a massive concentration of sound wave-fronts moving
  along behind the jet (heard as a "sonic boom"). So we really do
  expect that waves satisfy assumption 1! Given that light behaves in
  many ways like a wave, it's a reasonable assumption to make of
  light. Of course, explanation 2 is just explanation 1 in disguise,
  without the mathematical dressing.

So much for theory and expectation: can we do an experiment to
determine whether the speed of light is constant or if it depends on
the velocity of the light source as Ritz conjectured? De Sitter (1913)
explains a very simple experiment which supports the hypothesis that
light moves at a constant speed.

** De Sitter's experiment

Consider a distant binary star system (two stars, A and B, orbiting
each other) and assume that the orbits of the stars obey Kepler's laws
(so they trace out ellipses). Assume Ritz's theory so that the speed
of light depends on the velocity of the star. When star A is moving
towards us (at speed $v$) in its orbit, the light it emits in our
direction will be moving at speed $c+v$. When it is moving away from
us (also at speed $v$), the light it emits in our direction will be
moving slower, with speed $c-v$. Therefore the motion will appear very
nonuniform: the star will seem to speed up as it comes towards us and
slow down as it moves away. This is not consistent with what we
observe in practice, which is uniform Keplerian motion. This means
that Ritz's theory cannot be an accurate description of the motion of
light.

This is an incredibly simple explanation. There are many ways in which
you could criticise this argument (maybe the motion we see is the
result of Ritz's theory and highly eccentric elliptical orbits?) and
he gives a more detailed argument with reference to specific binary
systems in a follow-up paper. In this follow-up paper he phrases the
conclusion slightly more conservatively: one can put an upper bound on
the dependence of the speed of light on the velocity of its source
using astronomical observations of binary systems according to the
argument sketched above.

Of course, there are many other experiments which confirm the
predictions of special relativity, but this one has the advantage that
it only requires you to have a good telescope rather than some
complicated configuration of interferometers. It's also the simplest
imaginable experiment you could design to directly test the constancy
of the speed of light: essentially racing lightbeams against one
another!

** References

- De Sitter, W. "A proof of the constancy of the velocity of light",
  Proceedings of the Royal Netherlands Academy of Arts and Sciences,
  1913, 15 II: 1297-1298, [[https://en.wikisource.org/wiki/A_proof_of_the_constancy_of_the_velocity_of_light][link]]

- De Sitter , W."On the constancy of the velocity of light",
  Proceedings of the Royal Netherlands Academy of Arts and Sciences,
  1913, 16 I: 395-396, [[https://en.wikisource.org/wiki/On_the_constancy_of_the_velocity_of_light][link]]

- Einstein, A. "Zur Elektrodynamik bewegter Körper", Annalen der
  Physik (1905) 322 (10): 891–921. A 1920 English translation by
  Meghnad Saha is available at this [[https://en.wikisource.org/wiki/On_the_Electrodynamics_of_Moving_Bodies_(1920_edition)][link]]

- Michelson, A. A.; Morley, E. W. "On the Relative Motion of the Earth
  and the Luminiferous Ether". American Journal of Science (1887)
  34:333–345, [[https://en.m.wikisource.org/wiki/On_the_Relative_Motion_of_the_Earth_and_the_Luminiferous_Ether][link]]

- Ritz, W. "Recherches critiques sur l'Électrodynamique Générale",
  Annales de Chimie et de Physique (1908) 13:145–275. [[http://gallica.bnf.fr/ark:/12148/bpt6k349439.image.f143][link]]
