#+SETUPFILE: ../aux/head.org
#+TITLE: UCL Geometry and Topology Open Day talk: Floer theory

* UCL Geometry and Topology Open Day talk: Floer theory

[2012-11-13 Tue]

These are the notes from the twenty minute talk I'm going to give at
the UCL Geometry and Topology Open Day for prospective PhD students
(November 14th 2012). For those who are interested in reading more,
check out Milnor's book on Morse theory and Atiyah's early survey
paper on Floer theory.

Given a function $F\colon\mathbf{R}^n\to\mathbf{R}$, the most
interesting points we can study are its critical points, in other
words the points where all the partial derivatives vanish:
\[\frac{\partial F}{\partial x_1}=\frac{\partial F}{\partial
x_2}=\cdots=\frac{\partial F}{\partial x_n}=0\]

For example, if $F(x,y)=x^2-y^2$ so that $\partial F/\partial x=2x$,
$\partial F/\partial y=-2y$, then the only critical point is
$x=y=0$. If we draw level sets of $F$ (the contours of $F$ considered
as a height function) then the level sets undergo a significant change
when we look a little below and a little above the critical
height 0. This particular critical point is called a saddle point (for
obvious reasons when you look at a picture of its graph).

This is the first indication of a deep relationship between the
critical points of a function and the topology (or shape) of the
domain of the function. Of course we could consider functions on more
interesting spaces than $\mathbf{R}^n$. For instance, the height
function on a sphere has two critical points (a maximum at the top, a
minimum at the bottom) and the height function on a torus has four (a
max, a min and two saddle points). You can tell what kind of critical
point you have by looking at the number of downward directions of the
function at the critical point: at a maximum on the torus there are
two downward directions, at a saddle there is one downward direction
and at a minimum there are none. To be more precise we need to recall
the second derivative test which says that the Taylor expansion of a
function around a critical point is dominated by its Hessian
matrix. Negative eigenvalues of the Hessian mean downward directions
(eigendirections) of the function, positive eigenvalues mean upward
directions. Let's define the index of a critical point to be the
number of negative eigenvalues of the Hessian at that point.

The deep relationship between critical points and topology is due to
Morse:

#+BEGIN_Theorem
  Suppose that $F\colon M\to\mathbf{R}$ is a function on a manifold
  $M$ and that, for all critical points, the Hessian matrix has no
  zero eigenvalues (nondegeneracy). Then there are at least $b_i$
  critical points with index $i$ where $b_i$ is a purely topological
  quantity called the $i$th Betti number, counting the number of
  "linearly independent $i$-dimensional holes".
#+END_Theorem

For instance, in a torus there are two "linearly independent
1-dimensional holes" and in our example we had two critical points of
index 1 (saddles). Conversely, with a little more information about
the gradient flowlines of the function, one can say something about
the topology of M from data about the function F and this is a very
fruitful piece of topology which you can read about in Milnor's
classic textbook on Morse theory.

More interestingly, one can study functions on infinite-dimensional
spaces $M$. For example, $M$ might be the space of paths
$\gamma\colon[0,1]\to K$ in a Riemannian manifold $K$ with fixed
endpoints and the function $F$ might be the length functional
\[F(\gamma)=\int_0^1|\dot{\gamma}(t)|dt\] The critical points of this
functional are familiar: they are the solutions to the Euler-Lagrange
equation, in other words the geodesic paths. In this case you can
still make sense of the index of a critical point – though $M$ is
infinite-dimensional, there are only a finite-dimensional space of
downward directions. Indeed when $\gamma$ is length-minimising there are
no downward directions! Using this kind of Morse theory on the
loopspaces of certain homogeneous spaces, Bott was able to prove his
remarkable periodicity theorem for the homotopy groups of the
orthogonal and unitary groups.

Yet more interesting is the case when the index becomes infinite, the
case when your critical points have infinitely many upward and
infinitely many downward directions. This is called Floer theory or
semi-infinite Morse theory, and is significantly harder. Let me give
you an example.

Let $H\colon\mathbf{R}^3\to\mathbf{R}$ be a function. On the space of
$2\pi$-periodic functions $\mathbf{R}\to\mathbf{R}^2$, in coordinates
$t\mapsto (p(t),q(t))$, you can define the symplectic action
functional
\[(p,q)\mapsto\int_0^{2\pi}(p(t)\dot{q}(t)-H(t,p(t),q(t)))dt\] The
Euler-Lagrange equations are \[\frac{\partial L}{\partial
p}=\frac{d}{dt}\frac{\partial L}{\partial\dot{p}},\qquad\frac{\partial
L}{\partial q}=\frac{d}{dt}\frac{\partial L}{\partial\dot{q}}\] which
become \[\dot{q}=\frac{\partial H}{\partial
p},\qquad\dot{p}=-\frac{\partial H}{\partial q}\] These you may
recognise as Hamilton's equations of motion for the Hamiltonian
function $H$. So a critical point of the symplectic action functional
is a $2\pi$-periodic orbit of this Hamiltonian system. Let me convince
you that it has infinite index, at least when $H\equiv 0$. Let
$p(t)=\sum_{k=-\infty}^{\infty}p_k^{ikt}$ and
$q(t)=\sum_{k=-\infty}^{\infty}q_ke^{ikt}$ where $p_{-k}=\bar{p}_k$
and $q_{-k}=\bar{q}_k$ are the Fourier coefficients. Then
\[F(p+\delta,q+\epsilon)=\sum_k\sum_{\ell}(p_k+\delta_k)i\ell(q_\ell+\epsilon_{\ell})\int_0^{2\pi}e^{i(k+\ell)t}dt\]
The integral is nonzero only when $k=-\ell$, when it is $\pi$, so this
becomes
\[F(p+\delta,q+\epsilon)=\sum_{k=-\infty}^{\infty}k\pi(p_k+\delta_k)(q_k+\epsilon_k)\]
This is
\[F(p+\delta,q+\epsilon)=\pi\sum_{k=-\infty}^{\infty}(kp_kq_k+k(p_k\epsilon_k+q_k\delta_k)+k\delta_k\epsilon_k)\]
The Hessian is (twice) the quadratic part of this. If we define
\[\mathbf{H}=\pi\left(\begin{array}{ccccccc} \ddots & 0 & 0 & 0 & 0 &
0 & 0\\ 0 & -2 &0 &0 & 0 & 0 & 0 \\ 0 & 0 & -1&0 &0 & 0 & 0 \\ 0 & 0 &
0 & 0 &0 &0 & 0 \\ 0 & 0 & 0 & 0 &1 &0 & 0 \\ 0 & 0 & 0 & 0 &0 &2 & 0
\\ 0 & 0 & 0 & 0 &0 &0 & \ddots \end{array}\right)\] then the Hessian
is \[\left(\begin{array}{cc}\delta
&\epsilon\end{array}\right)\left(\begin{array}{cc}0 &
\mathbf{H}\\ \mathbf{H} &
0\end{array}\right)\left(\begin{array}{c}\delta\\ \epsilon\end{array}\right)\]
and we see that the Hessian is an infinite matrix with infinitely many
positive and negative eigenvalues!

Floer's idea was to prove some kind of invariance of this theory under
deformations of $H$, which allowed him to compare the number of critical
points (periodic orbits) for an arbitrary $H$ to the number of periodic
orbits for a particular H he could understand. He used this to prove
the Arnold conjecture: a highly nontrivial lower bound on the number
of periodic orbits.

Morse theory is related by Morse's theorem to the topology of a
manifold. One exciting open problem is to understand the topology of
"semi-infinite cycles" and their intersection theory, which is what
Floer's theory seems to capture. A slighty more precise version of
this open problem goes by the name of the Atiyah-Floer conjecture. You
can read about it here:

- M. F. Atiyah, "New invariants of 3- and 4-dimensional manifolds" in
  The Mathematical Heritage of Hermann Weyl (Proceedings of Symposia
  in Pure Mathematics, Volume 48) 1988 p. 285 – 300


