#+SETUPFILE: ../aux/head.org
#+TITLE: What is a quantum field?

* What is a quantum field?

[2017-09-24 Sun]

As a mathematician trying to learn QFT, a question that always
bothered me was "what is a quantum field?". In mathematics, we like to
have a precise idea of what kind of objects we are working with (is it
a set? is it a function? is it a topological space?). In QFT, the
analytical difficulties in making the definition precise for even the
simplest nontrivial theories are substantial; as a result, there are
two standard attitudes to the question which are implicit in the way
people write books about the subject:

- The first, completely reasonable, attitude is: "We will introduce
  the formalism and show you how to perform computations: that's
  what's important. What you do with the formalism in the privacy of
  your own room is your business."
- The second, also completely reasonable, attitude is: "We have
  thought long and hard about this, and the following is the cleanest
  and most beautiful axiomatisation of the subject we could find; we
  wish you the best of luck unpicking this."

Below, I will try and explain that the question does have a
reasonable, intuitive answer, which you can explain without going too
deeply into the analytical details. The moral is that there is
actually no difference between quantisation in ordinary quantum
mechanics and in QFT: there should be a Hilbert space of wavefunctions
and some operators, the only difference is that the wavefunctions are
defined on an infinite-dimensional space of field configurations (so
we call them "wavefunctionals").

I will start by reviewing quantisation in ordinary quantum mechanics,
before moving on to the simplest QFT (the Klein-Gordon field) and
explaining the wavefunctional picture. Hopefully, once you have seen
this intuition, the abstract frameworks built by books like
Glimm-Jaffe or Streater-Wightman will make more sense.

** Review of quantisation

When we /quantise/, we start with a classical system and try to
construct a quantum mechanical system which reduces to this classical
system in the $\hbar\to 0$ limit. Of course, it's not clear that there
is an answer, let alone a unique answer, or that there will be some
prescriptive way to find the answer for an arbitrary classical system,
even if it exists.

Nonetheless, let's review the basic set-up:

- A classical mechanical system comprises a phase space (symplectic
  manifold $(M,\omega)$) of positions and momenta; observable
  quantities are functions on this phase space. There is a
  distinguished function $H$ called the Hamiltonian which governs time
  evolution of the system. Explicitly, the Hamiltonian generates a
  Hamiltonian vector field $X_H$ on the phase space via Hamilton's
  equations $\omega(X_H,-)=-dH$ and integrating this vector field
  gives a flow $\phi_H^t\colon M\to M$ which is the time evolution of
  the system.
- A quantum mechanical system comprises a Hilbert space together with
  a collection of operators whose spectrum (eigenstates/eigenvalues)
  you want to compute. There is a distinguished operator $H$ called
  the Hamiltonian which governs time evolution of the system. In the
  Schr\ouml{}dinger picture, this time evolution works as
  follows. The Hamiltonian generates a one-parameter family of unitary
  transformations $U_t$ satisfying the Schr\ouml{}dinger equation
  \[\frac{dU_t}{dt}=\frac{i}{\hbar}HU_t.\] (Unitarity of the
  transformation is equivalent to $H$ being Hermitian). For example,
  if $H$ is time-independent then $U_t=e^{iHt/\hbar}$. If the system
  is in the state $\psi$ at time $0$ then at time $t$ it will be in
  the state $U_t\psi$.

** Canonical quantisation of the free particle

The most basic classical system is a particle living in a
1-dimensional space with coordinate $q$. The phase space keeps track
of the position $q$ but also the momentum $p$, so it is $\mathbf{R}^2$ with
coordinates $p,q$ and symplectic form $\omega=dp\wedge dq$. We want to
turn this into a quantum system by finding a suitable Hilbert space
and turning functions of $q,p$ into operators on this Hilbert space.

We take our Hilbert space to be the space of square-integrable
/wavefunctions/ of $q$, written $L^2(\mathbf{R})$. The two most famous
wavefunctions, whose physical interpretation is clear, actually don't
live in this space (but can be closely approximated by wavefunctions
in $L^2$):
- Fix a point $q_0\in\mathbf{R}$. The delta function $\delta(q-q_0)$ should
  represent something like a particle localised at the point
  $q_0$. Delta functions are not really functions at all, let alone
  square-integrable, but one can approximate a delta function
  arbitrarily closely by a strongly peaked Gaussian.
- Fix a frequency $\omega$. The function $e^{i2\pi\omega q}$ is a wave
  with pure frequency $\omega$. This should represent a particle (like
  a photon) whose momentum is $\omega$. To see why, recall:
  + De Broglie's formula $E=h\omega$ ($h=2\pi$ in our units) relating
    the energy and frequency of matter waves,
  + the fact that a light wave has energy equal to its momentum (up to
    a factor of $c=1$) since its energy-momentum vector lives on the
    null-cone in spacetime.
  Again, this wavefunction is not square-integrable, but you could cut
  it off outside a large ball to get a reasonably good approximation.

We want these wavefunctions to be eigenfunctions of the operators
$\hat{q}$ and $\hat{p}$ corresponding to position and momentum, with
eigenvalues $q_0$ and $p=2\pi\omega$ respectively.

The wavefunction $\delta(x-q_0)$ is the unique $q_0$-eigenfunction of
the operator $(\hat{q}\psi)(q)=q\psi(q)$. The wavefunction $e^{ipx}$ is the
unique $p$-eigenfunction of the operator
$\hat{p}\psi=-i\partial_q\psi$. The standard guess at a quantisation of
this phase space is therefore to replace $q$ and $p$ by the operators
$\hat{q}$ and $\hat{p}$ defined above, acting on the Hilbert space of
$L^2$-functions of $q$.

If $P$ is a polynomial in $p$ and $q$ then we can try replacing $P$ by
the corresponding polynomial in the operators $\hat{p}$ and
$\hat{q}$. Alas, the operators $\hat{p}$ and $\hat{q}$ no longer
commute, indeed, we have
\[[\hat{q},\hat{p}]=i,\]
so there are many choices of how to order the operators in
the polynomial $P$. For an example of how one quantises a particular
quadratic Hamiltonian $H=\frac{1}{2}p^2+\omega^2q^2$, see my pre-QFT
post on the [[./shm.org][simple harmonic oscillator]].

** Quantum field theory

Let us now turn to the problem of finding a quantum system to replace
the classical /Klein-Gordon field/. The Klein-Gordon field is a
complex-valued function $\phi(x)$. The classical Hamiltonian
associated to this field is \[\frac{1}{2}\int
d^3x\left(\pi^2+|\nabla\phi|^2+m^2\phi^2\right).\] The quantity $\pi$
is the analogue of "momentum" for a field: in the case of the
Klein-Gordon field, it is just the time-derivative of $\phi$ (just as
momentum is related to the time derivative of $q$).

When we quantised a free particle, our Hamiltonian was a function on
the space of possible positions and momenta of the particle.

Now we are quantising a field, the Hamiltonian is a function on the
space of possible configurations and momenta of the field.

When we quantised a free particle, we took as our Hilbert space the
space of wavefunctions on $\mathbf{R}^3$, where $\mathbf{R}^3$ is the
space of possible configurations (positions) of our particle.

Now we are quantising a field, we will take as our Hilbert space the
space of wavefunctions on $\mathcal{F}$, the space of possible
configurations of the field.

A configuration of the field is just a complex-valued function on
$\mathbf{R}^3$. In other words, $\mathcal{F}$ is a suitable space of
functions $\phi(x)$. A wavefunction will be a map
$\Psi\colon\mathcal{F}\to\mathbf{C}$; something which eats a function
$\phi$ and outputs a number, for example: \[\Psi(\phi)=\int
d^3x\phi(x).\] To distinguish the functions
$\phi\colon\mathbf{R}^3\to\mathbf{C}$ from the wavefunctions
$\Psi\colon\mathcal{F}\to\mathbf{C}$, we will call $\Psi$ a
/wavefunctional/. The suffix /-al/ denotes a function which eats
functions and outputs numbers.

Just as a wavefunction in quantum mechanics describes some kind of
superposition of particles at different points, the wavefunctional in
QFT describes a superposition of field configurations.

I am not going to address the questions "which wavefunctionals do we
allow?" or "what is the inner product making them into a Hilbert
space?", nor will I talk about normalising wavefunctionals; therein
lie some analytical issues. Instead, here are some examples of
wavefunctionals.

- Given a function $f\in\mathcal{F}$, there is a delta-functional
  $\delta(\phi-f)$ concentrated at $f$ (which vanishes unless
  $\phi\equiv f$). This probably shouldn't be allowed in the rigorous
  theory, in the same way that the delta function $\delta(q-q_0)$ is
  not an $L^2$-function; nonetheless, it's a convenient storytelling
  device. You can imagine this as a QFT state where the field has a
  definite value $f(x)$ at each point $x$ (in the same way that the
  delta function $\delta(q-q_0)$ is a quantum mechanical state where the
  particle has definite position $q_0$).
- Given a function $\lambda(x)$, the wavefunctional
  $\Psi(\phi)=\exp(i\int d^3x\lambda(x)\phi(x))$ is going to be a QFT
  state where the field has definite "momentum" $\pi=\lambda$. This is
  analogous to the quantum mechanical "plane wave" state
  $\psi(x)=e^{ipx}$, which has momentum $p$.

Here are some examples of classical observables for fields and the
corresponding QFT operators.

#+BEGIN_exm
  The function $ev_x\colon\mathcal{F}\to\mathbf{C}$ ("evaluation at
  $x$") is defined by $ev_x\phi=\phi(x)$. This is the field theory
  analogue of the position function $q$ for a free particle. What is
  the operator associated to $ev_x$ in QFT?  When we quantised $q$ we
  used $(\hat{q}\psi)(x)=x\psi(x)$. Consider the operator
  $\widehat{ev_x}$ defined by
  \[(\widehat{ev_x}\Psi)(\phi)=\phi(x)\Psi.\] The wavefunctional
  $\Psi$ is a $\lambda$-eigenstate of $\widehat{ev_x}$ if and only if
  $\phi(x)\Psi(\phi)=\lambda\Psi(\phi)$ for all
  $\phi\in\mathcal{F}$. This means that $\Psi$ must vanish on $\phi$
  unless $\phi(x)=\lambda$. For example, we see that, if
  $f\in\mathcal{F}$ is a function, the delta-functional
  $\Psi(\phi)=\delta(\phi-f)$ is a simultaneous eigenstate for
  $\widehat{ev_x}$ for all $x$, with eigenvalues $f(x)$. This operator
  is usually called $\phi(x)$ in QFT textbooks.
#+END_exm

#+BEGIN_exm
  There are also classical field observables $ev_g(\phi)=\int
  d^3xg(x)\phi(x)$ defined for any "smearing function" $g$, which
  averages the values of $\phi$ over the support of $g$, weighted by
  $g$. The corresponding operator should be
  \[(\widehat{ev_g}\Psi)(\phi)=\left(\int d^3xg\phi\right)\Psi(\phi).\] For
  example, the operator $\widehat{ev_x}$ we already defined
  corresponds to $g=\delta_x$, the delta function at $x$. The
  map sending $g$ to the operator $\widehat{ev_g}$ is, I think
  what people mean when they talk about a quantum field as being an
  /operator-valued distribution/.
#+END_exm

#+BEGIN_exm
  There should be an operator corresponding to the momentum $\pi$,
  and, by analogy with usual quantum mechanics, it should be
  $-i\partial$. However, now $\partial$ means differentiation in the
  space $\mathcal{F}$ of functions. Given a wavefunctional
  $\Psi\colon\mathcal{F}\to\mathbf{C}$ and functions
  $f,\phi\in\mathcal{F}$, we define the directional derivative
  $(d_\phi\Psi)(f)$ of $\Psi$ at $\phi$ in the $f$-direction to be
  \[\left.\frac{d}{dt}\right|_{t=0}\Psi(\phi+tf).\] When
  $f(x)=\delta(x-x_0)$ is the delta function at $x_0$, this is often
  written as \[\frac{\delta\Psi}{\delta\phi(x_0)}.\] The operator
  corresponding to field momentum at $x$ will be
  $-i\frac{\delta}{\delta\phi(x)}$. The state \[\Psi(\phi)=e^{i\int
  d^3x\phi(x)\lambda(x)}\] is a simultaneous eigenstate for all these
  momentum operators, with eigenvalues $\lambda(x)$. To see this, note
  that
  \begin{align*}
  \lim_{t\to 0} \frac{e^{i\int d^3x(\phi(x)+t\delta(x))\lambda(x)}-e^{i\int d^3x\phi(x)\lambda(x)}}{t}
  &=e^{i\int d^3x\phi(x)\lambda(x)}\lim_{t\to 0}\frac{e^{it\int d^3x\delta(x)\lambda(x)}-1}{t}\\
  &=e^{i\int d^3x\phi(x)\lambda(x)}i\lambda(x),
  \end{align*}
  so
  \[-i\frac{\delta\Psi}{\delta\phi(x)}(\phi)=\lambda(x)\Psi(\phi).\]
#+END_exm

Finally, we turn to the most important operator in the theory of the
Klein-Gordon field, the Hamiltonian.

#+BEGIN_lma
  We can rewrite the
  classical Hamiltonian
  \[H=\frac{1}{2}\int d^3x\left(\pi^2+|\nabla\phi|^2+m^2\phi^2\right)\]
  as
  \[H=\frac{1}{(2\pi)^3}\int d^3k a(k)^\dagger a(k),\]
  where
  \begin{align*}
  a(k)&=\int d^3x e^{ik\cdot x}\left(\omega_k\phi(x)-i\pi(x)\right)\\
  a(k)^{\dagger}&=\int d^3x e^{-ik\cdot x}\left(\omega_k\phi(x)+i\pi(x)\right)\\
  \omega_k&=\sqrt{|k|^2+m}.
  \end{align*}
#+END_lma

#+BEGIN_proof
  We have
  \[
  \int\frac{d^3k}{(2\pi)^3}a(k)^\dagger a(k)=\int\int\int\frac{d^3k}{(2\pi)^3}d^3xd^3ye^{ik\cdot(x-y)}\left(\omega_k\phi(x)-i\pi(x)\right)\left(\omega_k\phi(x)+i\pi(x)\right)
  \]
  Multiplying out gives four terms:
  - The terms $\int\int\int
    d^3kd^3xd^3e^{ik\cdot(x-y)}yi\pi(y)\omega_k\phi(x)$ and
    $-\int\int\int d^3kx^3xd^3ye^{ik\cdot(x-y)}i\pi(x)\omega_k\phi(y)$
    cancel. To see this, take the second term, switch
    $x\leftrightarrow y$ and change $k\leftrightarrow -k$. The
    integrand becomes the integrand in the first term, the volume form
    $d^3kd^xd^3y$ is invariant, so the terms cancel because one
    appears with a minus sign.
  - The term
    \[\int\int\int\frac{d^3k}{(2\pi)^3}d^3xd^3ye^{ik\cdot(x-y)}\pi(x)\pi(y),\]
    becomes
    \[\int d^3x\pi(x)^2,\]
    using the identity
    \[\delta(x-y)=\int\frac{d^3k}{(2\pi)^3}e^{ik\cdot(x-y)}.\]
  - The term
    \[\int\int\int\frac{d^3k}{(2\pi)^3}d^3xd^3ye^{ik\cdot(x-y)}\left(|k|^2+m^2\right)\phi(x)\phi(y),\]
    becomes
    \[\int d^3x\left(|\nabla\phi|^2+m^2\right)\phi^2,\]
    using the standard trick in Fourier theory of exchanging
    derivatives for factors of $k$.
#+END_proof

When we quantise, we turn $a(k)$ and $a(k)^\dagger$ into operators
\[\widehat{a(k)}=\int d^3xe^{ik\cdot
x}\left(\omega_k\phi(x)+\frac{\delta}{\delta\phi(x)}\right),\qquad
\widehat{a(k)}^\dagger=\int d^3xe^{-ik\cdot
x}\left(\omega_k\phi(x)-\frac{\delta}{\delta\phi(x)}\right).\] This
notation has been chosen to suggest a formal similarity with the
simple harmonic oscillator system, reviewed in [[./shm.html][another blog post]]. As
with that system, there is a /lowest-energy (or vacuum) state/
$\Psi_0$ which is annihilated by the operator $\widehat{a(k)}$, and
therefore satisfies
\[\hat{H}\Psi_0=\int\frac{d^3k}{(2\pi)^3}a(k)^\dagger a(k)\Psi_0=0.\]
One can generate other states by acting on the vacuum with
$\widehat{a(k)^\dagger}$, $\widehat{ev_x}$ or combinations of these
operators. The state \[\widehat{a(k)}^\dagger\Psi_0\] has the
interpretation of a single particle with momentum $k$. The state
$\widehat{ev_x}\Psi_0$ has the interpretation of a single particle at
$x$.

#+BEGIN_thm
  The wavefunctional
  \[\Psi_0(\phi)=\exp\left(-\int\int\int\frac{d^3k}{(2\pi)^3}d^3xd^3y
  e^{ik\cdot(x-y)}\frac{\omega_k}{2}\phi(x)\phi(y)\right)\] is a
  vacuum state of the quantised Klein-Gordon theory (i.e. it is
  annihilated by $\widehat{a(k)}$ for all $k$).
#+END_thm
#+BEGIN_proof
  We have
  \begin{align*}
    \frac{\delta\Psi_0}{\delta\phi(z)}(\phi)&=
    -\int\int\int\frac{d^3k}{(2\pi)^3}d^3x d^3y e^{ik\cdot(x-y)}\frac{\omega_k}{2}
     \left(\delta(x-z)\phi(y)+\phi(x)\delta(y-z)\right)\Psi_0(\phi)\\
    &=-\omega_k\phi(z)\Psi_0(\phi),
  \end{align*}
  so if we apply $\widehat{a(k)}$ to $\Psi_0$, we obtain
  \begin{align*}
    \widehat{a(k)}\Psi_0&=
      \int d^3z e^{ik\cdot z}\left(\omega_k\phi(z)+\frac{\delta}{\delta\phi(z)}\right)\Psi_0\\
    &=\int d^3z(\omega_k\phi(z)-\omega_k\phi(z))\\
    &=0.
  \end{align*}
#+END_proof

Note that this wavefunctional is even nicer if you write it in terms
of the Fourier transform $\tilde{\phi}(k)$ of $\phi(x)$:
\[\Psi_0(\phi)=\exp\left(-\int\frac{d^3k}{(2\pi)^3}\frac{\omega_k}{2}\tilde{\phi}(k)^2\right),\]
where we have used the fact that $\tilde{\phi}(k)=\tilde{\phi}(-k)$
since $\phi$ is real.


** Conclusion

The aim of all this was to show that, if you understand quantum
mechanics, you can also understand quantum field theory (in
principle!). The ideas are the same, but the wavefunctionals of QFT
are on a different plane of difficulty: they are functions on the
infinite-dimensional space of field configurations. To solve an
eigenvalue problem in this context means solving an
infinite-dimensional differential equation (like
$\widehat{a(k)}\Psi_0=0$ in the final theorem).

For more on this, there is an excellent physics textbook which covers
this material (thereby taking neither of the attitudes described in
the first paragraph). Chapter 10 covers the material I described
above:

- Hatfield "The quantum field theory of point particles and
  strings."  Frontiers in Physics, Perseus, 1998.

The classic book by Glimm and Jaffe also covers this from a
mathematical standpoint (and addresses issues which we glossed over
regarding integration of wavefunctionals); Chapter 6 covers the
material I described above:

- Glimm and Jaffe, "Quantum physics: a functional integral point of
  view", Springer Verlag, 1987.

For completeness, the other resources I have found most helpful for
learning about QFT are:

- [[http://www.damtp.cam.ac.uk/user/tong/qft.html][David Tong's lecture notes on QFT]].
- Peskin and Schroeder, "An introduction to quantum field theory",
  Avalon, 1995.
- Ryder, "Quantum field theory", Cambridge University Press, Second
  Edition 1996.
